"""update tg_user table

Revision ID: 0171d349295d
Revises: 875fe59478b4
Create Date: 2022-10-02 20:40:28.123022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0171d349295d'
down_revision = '875fe59478b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('tg_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_user', 'tg_id')
    # ### end Alembic commands ###
