"""add message_id

Revision ID: d56069d1c794
Revises: b035098c74f5
Create Date: 2022-10-11 15:20:15.586530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56069d1c794'
down_revision = 'b035098c74f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('words_stat', sa.Column('message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words_stat', 'message_id')
    # ### end Alembic commands ###